"""New DataBase

Revision ID: 5012aa295e14
Revises: 
Create Date: 2023-04-11 21:58:07.171902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5012aa295e14'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
                    sa.Column('owner_id', sa.Integer(), nullable=False),
                    sa.Column('brand', sa.String(), nullable=False),
                    sa.Column('model', sa.String(), nullable=False),
                    sa.Column('comfort_level', sa.Integer(), nullable=False),
                    sa.Column('for_kids', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('owner_id')
    )
    op.create_table('the_roles_of_a_user',
                    sa.Column('role', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('role')
    )
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('first_name', sa.String(), nullable=False),
                    sa.Column('middle_name', sa.String(), nullable=False),
                    sa.Column('last_name', sa.String(), nullable=False),
                    sa.Column('link_to_photo', sa.String(), nullable=True),
                    sa.Column('phone_number', sa.String(), nullable=False),
                    sa.Column('registered_at', sa.TIMESTAMP(), nullable=True),
                    sa.Column('current_role', sa.String(), nullable=True),
                    sa.Column('password', sa.String(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('is_superuser', sa.Boolean(), nullable=True),
                    sa.Column('is_verified', sa.Boolean(), nullable=True),
                    sa.ForeignKeyConstraint(['current_role'], ['the_roles_of_a_user.role'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('the_roles_of_a_user')
    op.drop_table('cars')
    # ### end Alembic commands ###
