"""Added Routes

Revision ID: 85af6843af77
Revises: 5012aa295e14
Create Date: 2023-04-12 12:41:11.097374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85af6843af77'
down_revision = '5012aa295e14'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
                    sa.Column('route_id', sa.Integer(), nullable=False),
                    sa.Column('status', sa.String(), nullable=False),
                    sa.Column('creator_id', sa.Integer(), nullable=False),
                    sa.Column('user_role', sa.String(), nullable=False),
                    sa.Column('cost', sa.Float(), nullable=False),
                    sa.Column('public_at', sa.TIMESTAMP(), nullable=True),
                    sa.Column('time_of_leaving', sa.TIMESTAMP(), nullable=False),
                    sa.Column('place_of_leaving', sa.String(), nullable=False),
                    sa.Column('place_of_arrival', sa.String(), nullable=False),
                    sa.Column('grade', sa.Integer(), nullable=True),
                    sa.Column('comments', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('route_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routes')
    # ### end Alembic commands ###
